import ProtectRoute from "@/components/admin/ProtectRoute";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ProtectRoute>
          <main>{children}</main>
        </ProtectRoute>
      </body>
    </html>
  );
}
